vehicle_mass: 1.0
motor: f15

aero:
  air_density: 1.225
  drag_coeff: 0.35
  normal_force_coeff: 2
  pitch_damping_coeff: -0.1

cg:
  x: 0
  y: 0
  z: 0.45

cp:
  x: 0
  y: 0
  z: 0.20
  
# mass moment of inertia in kg*m^2
mmoi:
  Ixx: 0.015
  Iyy: 0.015
  Izz: 0.002

nose_cone:
  type: conical
  length: 0.25
  radius: 0.09

body_tube:
  type: cylinder
  length: 0.91
  radius: 0.09